### ISSUE TITLE
ubuntu22 安装 1.3.2 deb无法启动

### ISSUE THREAD

**Issue by crazyn2** [Kingtous/Fclash#18]
OS: ubuntu22.04 amd64 
```
sudo dpkg -i cn.kingtous.fclash.deb
```
之后，没有fclash的图标，也无法命令行`fclash`启动

**Comment by Kingtous** [comment]
可执行文件在`/opt/apps/cn.kingtous.fclash/files/fclash`，终端执行你看看报什么错

**Comment by crazyn2** [comment]
```
flutter: fclash work directory: /home/zby/.local/share/cn.kingtous.fclash/clash
GO: set home dir to %s /home/zby/.local/share/cn.kingtous.fclash/clash
INFO[0000] Mixed(http+socks) proxy listening at: 127.0.0.1:22346 
INFO[0000] RESTful API listening at: 127.0.0.1:22345    
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.other]: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 37924
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.get (package:dio/src/dio_mixin.dart:61)
#3      ClashService._getLog (package:fclash/service/clash_service.dart:227)
#4      ClashService.initDaemon (package:fclash/service/clash_service.dart:176)
#5      ClashService.init.<anonymous closure> (package:fclash/service/clash_service.dart:119)
#6      new Future.delayed.<anonymous closure> (dart:async/future.dart:424)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:643)
#1      _RootZone.runBinary (dart:async/zone.dart:1658)
#2      _FutureListener.handleError (dart:async/future_impl.dart:162)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#4      Future._propagateToListeners (dart:async/future_impl.dart:799)
#5      Future._completeError (dart:async/future_impl.dart:574)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#7      _Completer.completeError (dart:async/future_impl.dart:23)
#8      Future.any.onError (dart:async/future.dart:617)
#9      _RootZone.runBinary (dart:async/zone.dart:1658)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#12     Future._propagateToListeners (dart:async/future_impl.dart:799)
#13     Future._completeError (dart:async/future_impl.dart:574)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:519)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [DioErrorType.other]: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 37936
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      safeRequest (package:kommon/request/request.dart:50)
#3      Request.get (package:kommon/request/request.dart:76)
#4      ClashService.getCurrentClashConfig (package:fclash/service/clash_service.dart:145)
#5      ClashService.reload (package:fclash/service/clash_service.dart:151)
#6      ClashService.initDaemon (package:fclash/service/clash_service.dart:189)
#7      ClashService.init.<anonymous closure> (package:fclash/service/clash_service.dart:119)
#8      new Future.delayed.<anonymous closure> (dart:async/future.dart:424)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:643)
#1      _RootZone.runBinary (dart:async/zone.dart:1658)
#2      _FutureListener.handleError (dart:async/future_impl.dart:162)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#4      Future._propagateToListeners (dart:async/future_impl.dart:799)
#5      Future._completeError (dart:async/future_impl.dart:574)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#7      _Completer.completeError (dart:async/future_impl.dart:23)
#8      Future.any.onError (dart:async/future.dart:617)
#9      _RootZone.runBinary (dart:async/zone.dart:1658)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
#12     Future._propagateToListeners (dart:async/future_impl.dart:799)
#13     Future._completeError (dart:async/future_impl.dart:574)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:519)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```
无法打开setting，一直显示loading

用root权限启动没问题

**Comment by Kingtous** [comment]
我这复现了，我看看

**Comment by crazyn2** [comment]
1.3.1版本setting可以打开，但是黑暗模式没用

**Comment by simonjhy** [comment]
我用了1.3.1和1.3.2 ， setting页面打不开

**Comment by crazyn2** [comment]
ubuntu, 1.3.1用root权限可以打开setting

**Comment by Kingtous** [comment]
图标问题

为了符合deepin/uos规范，没有在/usr/share/application下放desktop文件。

可以自行在下面放这个
https://github.com/Kingtous/Fclash/blob/stable/debian/build-src/opt/apps/cn.kingtous.fclash/entries/applications/cn.kingtous.fclash.desktop

**Comment by Kingtous** [comment]
可以再试试1.3.6版本呢
